apiVersion: batch/v1  # Use the correct API version for CronJob
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "*/5 * * * *"  # Cron schedule (runs every 5 minutes)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: mybackupapp:latest # Replace with your Docker image name
            volumeMounts:
            - name: data-volume
              mountPath: /data  # Mount path for data volume
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pvc  # Name of PersistentVolumeClaim (PVC)
